CREATE TABLE "guilds" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "discord_native_id" bigint UNIQUE NOT NULL
);

CREATE TABLE "settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "guild" integer UNIQUE NOT NULL,
  "delete_original_message" boolean NOT NULL DEFAULT false,
  "mention_user_in_reply" boolean NOT NULL DEFAULT false,
  "fix_instagram" boolean NOT NULL DEFAULT true,
  "fix_reddit" boolean NOT NULL DEFAULT true,
  "fix_tiktok" boolean NOT NULL DEFAULT true,
  "fix_twitter" boolean NOT NULL DEFAULT true,
  "fix_yt_shorts" boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX ON "guilds" ("id");

CREATE UNIQUE INDEX ON "guilds" ("discord_native_id");

CREATE UNIQUE INDEX ON "settings" ("guild");

COMMENT ON COLUMN "guilds"."discord_native_id" IS 'Discord Server ID';

ALTER TABLE "settings" ADD FOREIGN KEY ("guild") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;
